POST localhost:8080/api/v1/collaterals
Content-Type: application/json

{
  "name": null,
  "currency": "EUR",
  "year": 2022,
  "value": 100000000,
  "type": "asset"

}

> {%
    client.global.set("resource_location_url", response.headers.valuesOf("Location")[0]);
%}

###
GET {{resource_location_url}}

###
GET localhost:8080/actuator/health